// The autopilot controls in a stand-in page with a stand-in API.
const vm = require('vm'), fs = require('fs'); const src = fs.readFileSync(process.argv[2], 'utf8');
let ok = true; const check = (n, c, x) => { ok = ok && !!c; console.log((c ? 'PASS ' : 'FAIL ') + n + (c ? '' : '  ' + JSON.stringify(x))); };
const OPTIONS = { screeners: { '3-8': { name: 'Dow 30', kind: 'stock' }, '3-100': { name: 'S&P 100', kind: 'stock' }, '7-1': { name: 'Crypto (top coins)', kind: 'crypto' } }, everyHours: [3, 6, 12, 24], holdDays: [2, 5, 10, 20, 60],
  risk: { 1: { name: 'Cautious', positions: 12, top: 5, stop: -5, take: 8, crypto: 0 }, 3: { name: 'Balanced', positions: 8, top: 10, stop: -10, take: 18, crypto: 0.25 }, 5: { name: 'Adventurous', positions: 4, top: 20, stop: -20, take: 45, crypto: 1 } } };
const kept = { userId: 'tester@x.com' };          // the stand-in for the browser's own storage: it survives a "refresh" (a new page())
function page(server) {
  const els = {}, handlers = {}, calls = []; const container = { innerHTML: '' }; let boxes = [];
  const document = { readyState: 'complete', getElementById: id => id === 'practice-autopilot' ? container : (els[id] || null), addEventListener: (t, f) => { (handlers[t] = handlers[t] || []).push(f); }, querySelectorAll: () => boxes };
  const fetchFake = async (url, opts) => { const b = JSON.parse(opts.body); calls.push(b); const r = server(b); return { ok: r.status === 200, status: r.status, json: async () => r.body }; };
  const ctx = { document, localStorage: { getItem: k => (k in kept ? kept[k] : null), setItem: (k, v) => { kept[k] = String(v); } }, fetch: fetchFake, console, setTimeout, clearTimeout, confirm: (m) => { ctx.asked = m; return ctx.answer !== false; }, Date, JSON, Math, Object, String, Array, parseInt, parseFloat, isNaN, Promise };
  ctx.window = ctx; ctx.practicePortfolio = { reloaded: 0, reload() { this.reloaded++; }, plans: null, extra: null, setPlans(list, extra) { this.plans = list; this.extra = extra; } };
  vm.createContext(ctx); vm.runInContext(src, ctx);
  const form = (d) => { Object.assign(els, { 'ap-enabled': { checked: d.enabled }, 'ap-risk': { value: String(d.risk) }, 'ap-budget': { value: String(d.budgetUsd) }, 'ap-period': { value: String(d.periodDays) }, 'ap-every': { value: String(d.everyHours) }, 'ap-hold': { value: String(d.maxHoldDays) }, 'ap-risk-text': { textContent: '' } }); boxes = Object.keys(OPTIONS.screeners).map(k => ({ checked: d.screeners.includes(k), getAttribute: () => k })); };
  const click = a => handlers.click.forEach(f => f({ target: { closest: s => s === '[data-ap]' ? { getAttribute: () => a, tagName: 'BUTTON' } : null }, preventDefault() {} }));
  const text = () => container.innerHTML.replace(/<[^>]+>/g, ' ').replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/\s+/g, ' ');
  return { container, handlers, calls, form, click, text, ctx, els };
}
const sleep = ms => new Promise(r => setTimeout(r, ms));
(async () => {
  let p = page(() => ({ status: 200, body: { success: true, allowed: false } })); await sleep(30);
  check('hidden for someone not allowed', p.container.innerHTML === '');
  const settings = { enabled: false, risk: 3, budgetUsd: 10000, periodDays: 10, everyHours: 24, maxHoldDays: 20, screeners: ['3-100'] };
  let stored = { settings: { ...settings }, state: {}, log: [] };
  const server = b => {
    if (b.action === 'get') return { status: 200, body: { success: true, allowed: true, options: OPTIONS, ...stored } };
    if (b.action === 'save') { stored.settings = b.settings; stored.log.push({ t: '2026-10-12T15:00:00Z', type: 'note', symbol: '', usd: 0, text: 'Autopilot on: Balanced level.' }); return { status: 200, body: { success: true, allowed: true, options: OPTIONS, ...stored } }; }
    if (b.action === 'run') { if (stored.fail) return { status: 429, body: { error: 'It checked in a moment ago. Try again in 10 minutes' } }; stored.state.lastRun = '2026-10-12T15:40:00Z'; stored.log.push({ t: '2026-10-12T15:40:00Z', type: 'buy', symbol: 'COP', usd: 1250, text: 'Rank 1 with <b>RSI 66</b> (S&P 100 rank 1, score +3.4; chosen by the AI model)' }, { t: '2026-10-12T15:40:00Z', type: 'sell', symbol: 'AMT', usd: 1100, text: 'Up +18.2% since it was bought. Put in $1,000.00, got back $1,182.00.' }); return { status: 200, body: { success: true, allowed: true, options: OPTIONS, summary: { bought: 1, sold: 1, decidedBy: 'ai' }, ...stored } }; }
  };
  p = page(server); await sleep(30);
  check('shows the controls, off by default', /AI autopilot/.test(p.text()) && /Balanced: spreads the budget over up to 8 holdings, looks at the top 10 of each screener, sells a holding at -10% or \+18%, up to 25% of the budget in coins \(the whole budget if only coin screeners are ticked\)\./.test(p.text()) && /Off\. Nothing is bought or sold automatically/.test(p.text()) && /<option value="24" selected>once a day/.test(p.container.innerHTML) && /data-ap="run"[^>]*disabled/.test(p.container.innerHTML), p.text().slice(0, 400));
  check('says plainly what it is', /fake money/.test(p.text()) && /Nothing here is advice/.test(p.text()));
  p.form({ ...settings, enabled: true, risk: 5, budgetUsd: 5000, periodDays: 5, everyHours: 12, maxHoldDays: 10, screeners: ['3-8', '7-1'] }); await p.ctx.practiceAutopilot.flush(); await sleep(30);
  const sent = p.calls.find(c => c.action === 'save');
  check('saves exactly what was set', JSON.stringify(sent.settings) === JSON.stringify({ enabled: true, risk: 5, budgetUsd: 5000, periodDays: 5, everyHours: 12, maxHoldDays: 10, screeners: ['3-8', '7-1'], aiSell: true, selfTune: true, emails: true, stopPct: null, takePct: null }) && /Autopilot switched on/.test(p.text()) && /On\. First check-in at the next hourly check\./.test(p.text()) && /Adventurous/.test(p.text()) && !/data-ap="run"[^>]*disabled/.test(p.container.innerHTML), sent);
  { const keep = stored.settings; p.form({ ...stored.settings, screeners: [] }); await p.ctx.practiceAutopilot.flush(); await sleep(30); check('no screener ticked is saved as it is, and it says what is missing', stored.settings.screeners.length === 0 && /On, but no screener is chosen yet\. Tick at least one below/.test(p.text()) && /Tick at least one screener for it to start/.test(p.text()) && /id="ap-run"[^>]*disabled/.test(p.container.innerHTML), p.text().slice(0, 300)); p.form(keep); await p.ctx.practiceAutopilot.flush(); await sleep(30); }
  p.form(stored.settings); p.click('run'); await sleep(30);
  check('check in now: shows what happened and refreshes the portfolio', /Checked in: 1 bought, 1 sold/.test(p.text()) && /Bought COP with \$1,250\. Rank 1 with &lt;b&gt;RSI 66&lt;\/b&gt;/.test(p.text()) && /Sold AMT \. Up \+18\.2%/.test(p.text()) && p.ctx.practicePortfolio.reloaded === 1 && /Last check-in/.test(p.text()) && !/<b>RSI/.test(p.container.innerHTML), p.text().slice(-500));
  stored.fail = true; p.form(stored.settings); p.click('run'); await sleep(30); check('too soon: says so', /checked in a moment ago/.test(p.text()));
  // every screener in groups, and the record it learns from
  const OPT2 = { ...OPTIONS, screeners: { '3-100': { name: 'S&P 100', kind: 'stock', group: 'US shares' }, '3-6': { name: 'Russell 2000 (small)', kind: 'stock', group: 'US shares' }, '4-200': { name: 'ASX 200', kind: 'stock', group: 'Australian shares' }, '5-ftse100': { name: 'UK FTSE 100', kind: 'stock', group: 'UK shares' }, '7-1': { name: 'Crypto (top coins)', kind: 'crypto', group: 'Coins' } } };
  const G = (label, n, avg, vs, beat) => ({ label, n, avg, vs, beat, judged: n, up: beat });
  const full = { settings: { ...settings, enabled: true, screeners: ['3-100', '4-200'] }, state: { lastRun: '2026-10-12T15:40:00Z' }, log: [], minSample: 8, resting: { '3-100': '2026-10-26T15:40:00Z' },
    scorecard: { ...G('all', 12, 1.84, -0.62, 5), groups: { screener: [G('S&P 100', 9, 0.9, -1.7, 3), G('ASX 200', 3, 4.6, 2.6, 2)], rank: [G('rank 1 to 3', 12, 1.84, -0.62, 5)], rsi: [G('RSI 45 to 60', 12, 1.84, -0.62, 5)], chosen: [G('chosen by the AI model', 12, 1.84, -0.62, 5)], exit: [G('sold at the loss limit', 4, -10.5, -11, 0)] } },
    lessons: { at: '2026-10-20T15:40:00Z', n: 10, items: ['Buys ranked 1 to 3 lagged the market by 0.6% on average over 12 trades <b>.', 'Too few ASX trades (3) to compare.'] }, recent: [] };
  let q = page(() => ({ status: 200, body: { success: true, allowed: true, options: OPT2, ...full } })); await sleep(30);
  check('screeners are listed under their markets', /US shares S&P 100 \(resting until [^)]*26[^)]*\) Russell 2000 \(small\) Australian shares ASX 200 UK shares UK FTSE 100 Coins Crypto \(top coins\)/.test(q.text()), q.text().slice(q.text().indexOf('Screeners it buys from'), q.text().indexOf('Screeners it buys from') + 260));
  check('how it is doing: what it holds and how its finished trades went, in plain profit and loss', /How it is doing Holding nothing right now\. 12 finished trades in all: 5 up, 7 down or level, average \+1\.8% each\./.test(q.text()) && !/too few to conclude/.test(q.text()), q.text().slice(q.text().indexOf('How it is doing'), q.text().indexOf('How it is doing') + 200));
  check('breakdown by screener, rank, RSI, who chose and how it was sold', ['By screener', 'Trades Average Up Against an index fund', 'S&P 100 9 \\+0\\.9% 3 of 9 -1\\.7%', 'ASX 200 3 \\+4\\.6% 2 of 3 \\+2\\.6%', 'By place in the ranking when bought', 'By RSI when bought', 'By who chose', 'By how it was sold', 'sold at the loss limit 4 -10\\.5% 0 of 4 -11\\.0%', 'A group needs 8 trades'].every(x => new RegExp(x).test(q.text())), q.text().slice(q.text().indexOf('Breakdown'), q.text().indexOf('Breakdown') + 500));
  check('its notes are shown, safely, with what they rest on', /What it has noted from its record \(written by the AI model on [^)]*20[^)]* from 10 finished trades\)/.test(q.text()) && /lagged the market by 0\.6% on average over 12 trades &lt;b&gt;/.test(q.container.innerHTML) && /Too few ASX trades/.test(q.text()));
  q = page(() => ({ status: 200, body: { success: true, allowed: true, options: OPT2, ...full, scorecard: { ...G('all', 3, -2.0, -1.0, 1), groups: {} }, lessons: null, resting: {} } })); await sleep(30);
  check('with few trades it says they are too few', /3 finished trades in all: 1 up, 2 down or level, average -2\.0% each\. Fewer than 8 trades: too few to conclude anything yet\./.test(q.text()) && !/What it has noted/.test(q.text()) && !/resting until/.test(q.text()), q.text().slice(q.text().indexOf('How it is doing'), q.text().indexOf('How it is doing') + 260));
  check('before any sale it explains what will appear', /Holding nothing right now\. No finished trades yet: nothing it bought has been sold\./.test(p.text()));
  // every change saves by itself: nothing to press, and a refresh shows what was last set
  { const st = { settings: { ...settings, screeners: [] }, state: {}, log: [], practiceCash: 100000 }; let saves = 0;
    const srv = b => { if (b.action === 'save') { saves++; if (st.down) return { status: 500, body: { error: 'Internal server error' } }; st.settings = { ...b.settings, budgetUsd: Math.round(b.settings.budgetUsd) }; } if (b.action === 'run') st.state.lastRun = '2026-10-12T15:40:00Z';
      const ready = st.settings.enabled && st.settings.screeners.length;
      return { status: 200, body: { success: true, allowed: true, options: OPTIONS, summary: { bought: 0, sold: 0 }, ...st, holding: ready ? { count: 3, investedUsd: 3750 } : { count: 0, investedUsd: 0 }, nextCheck: ready ? { at: '2026-10-12T14:40:00Z', markets: ['US'] } : null } }; };
    let w = page(srv); await sleep(30);
    const html = w.container.innerHTML;
    check('layout: a switch, labelled fields, level names, no save button', /class="ap-switch"/.test(html) && /id="ap-switch-text">Off</.test(html) && /<label class="ap-label" for="ap-budget">Budget for the AI<\/label>/.test(html) && /Build up to it over/.test(html) && /data-ap-level="3" class="now">Balanced</.test(html)
      && !/data-ap="save"/.test(html) && /id="ap-saved" class="ap-saved ">Changes are saved as you make them\. Use the switch at the top right to turn it on\.</.test(html) && /id="ap-run" data-ap="run" class="ap-btn " disabled title="Switch the autopilot on first"/.test(html), html.slice(html.indexOf('ap-actions'), html.indexOf('ap-actions') + 520));
    check('nothing is ticked for a new user', !/data-ap-screener="[^"]*" checked/.test(html) && /0 chosen/.test(w.text()));
    check('says what the settings mean in practice, from what is selected', /It checks in once a day\. Up to 8 holdings of about \$1,250 each: 1 at the first check-in, then more as the budget is released, all 8 after about 8 days\. Then the whole \$10,000 is in use\./.test(w.text()) && /It sells a holding once it has had it for 20 days, whatever the price, and sooner at -10% or \+18%, when a stop that follows a rising holding is hit \(it starts once the holding has risen beyond its own normal wobble and is set from how much that holding normally moves: wider for a jumpy coin, closer when its screener figures weaken or time is short\), or when its screener signal turns negative or it slips far down the ranking\. The money is then free for the next buy\./.test(w.text()), w.text().slice(w.text().indexOf('It checks in'), w.text().indexOf('It checks in') + 420));
    const stub = () => ({ disabled: false, textContent: '', title: '', classList: { on: {}, toggle(c, v) { this.on[c] = v; } } });
    const fire = (type, id) => w.handlers[type].forEach(f => f({ type, target: { id, getAttribute: () => null } }));
    Object.assign(w.els, { 'ap-run': stub(), 'ap-saved': stub(), 'ap-plan': stub(), 'ap-chosen': stub(), 'ap-status': stub(), 'ap-switch-text': stub() });
    w.form({ ...st.settings, budgetUsd: 20000.4, risk: 5 }); fire('input', 'ap-budget');
    check('typing: it says "Saving…" and waits for a pause before sending', w.els['ap-saved'].textContent === 'Saving…' && saves === 0 && /Up to 4 holdings of about \$5,000 each/.test(w.els['ap-plan'].textContent), [w.els['ap-saved'].textContent, saves]);
    await sleep(1100);
    check('after the pause it is saved without pressing anything', saves === 1 && st.settings.budgetUsd === 20000 && st.settings.risk === 5 && /✓ Saved\./.test(w.text()), [saves, st.settings, w.text().slice(w.text().indexOf('Check in now'), w.text().indexOf('Check in now') + 90)]);
    w.form({ ...st.settings, budgetUsd: 20000.4, risk: 5 }); await w.ctx.practiceAutopilot.flush(); await sleep(30);
    check('a value the server tidied (20000.4 to 20000) is not saved over and over', saves === 1, saves);
    w.form({ ...st.settings, screeners: ['3-8', '7-1'] }); fire('change', 'ap-screener'); await sleep(250);
    check('ticking a screener is saved almost at once', saves === 2 && JSON.stringify(st.settings.screeners) === JSON.stringify(['3-8', '7-1']), [saves, st.settings.screeners]);
    w = page(srv); await sleep(30);
    check('after a refresh the panel shows exactly what was last set', /data-ap-screener="3-8" checked/.test(w.container.innerHTML) && /data-ap-screener="7-1" checked/.test(w.container.innerHTML) && !/data-ap-screener="3-100" checked/.test(w.container.innerHTML) && /value="20000"/.test(w.container.innerHTML) && /data-ap-level="5" class="now"/.test(w.container.innerHTML) && /2 chosen/.test(w.text()));
    Object.assign(w.els, { 'ap-run': stub(), 'ap-saved': stub(), 'ap-plan': stub(), 'ap-chosen': stub(), 'ap-status': stub(), 'ap-switch-text': stub() });
    w.form({ ...st.settings, budgetUsd: 2000000 }); await w.ctx.practiceAutopilot.flush(); await sleep(30);
    check('a budget that makes no sense is not saved, and it says why', saves === 2 && w.els['ap-saved'].textContent === 'Not saved: the budget cannot be more than $1,000,000.' && w.els['ap-saved'].classList.on.bad === true, w.els['ap-saved'].textContent);
    w.form({ ...st.settings, enabled: true }); w.handlers.change.forEach(f => f({ type: 'change', target: { id: 'ap-enabled', getAttribute: () => null } })); await sleep(30);
    check('the switch saves at once and the panel says what happens next', saves === 3 && st.settings.enabled === true && /id="ap-switch-text">On</.test(w.container.innerHTML) && /class="ap-status on"/.test(w.container.innerHTML)
      && /On\. Holding 3 of up to 4: \$3,750 of the \$20,000 budget is invested\. Next check-in about [^.]*, when the US market is open\./.test(w.text()) && /Autopilot switched on\. Press "Check in now"/.test(w.text()) && /id="ap-run" data-ap="run" class="ap-btn primary"  title="Runs one check-in now/.test(w.container.innerHTML), w.text().slice(w.text().indexOf('On.'), w.text().indexOf('On.') + 220));
    w.form({ ...st.settings, risk: 2 }); w.click('run'); await sleep(60);
    check('check in now first saves what was just changed', saves === 4 && st.settings.risk === 2 && w.calls.map(c => c.action).slice(-2).join() === 'save,run' && /Checked in: 0 bought, 0 sold/.test(w.text()), w.calls.map(c => c.action));
    st.down = true; w.form({ ...st.settings, risk: 4 }); await w.ctx.practiceAutopilot.flush(); await sleep(30);
    check('if a save fails it says so and does not pretend', /Not saved: Internal server error/.test(w.text()) && /class="ap-saved bad"/.test(w.container.innerHTML) && st.settings.risk === 2, w.text().slice(w.text().indexOf('Check in now'), w.text().indexOf('Check in now') + 80));
    st.down = false; w.form({ ...st.settings, risk: 4 }); await w.ctx.practiceAutopilot.flush(); await sleep(30); check('and the next try goes through', st.settings.risk === 4 && /✓ Saved\./.test(w.text()));
    w.form({ ...st.settings, enabled: false }); w.handlers.change.forEach(f => f({ type: 'change', target: { id: 'ap-enabled', getAttribute: () => null } })); await sleep(30);
    check('switching off says its holdings stay', st.settings.enabled === false && /Autopilot switched off\. What it holds stays in the practice portfolio until you sell it\./.test(w.text()) && /Off\. Nothing is bought or sold automatically/.test(w.text()));
    w.form({ ...st.settings, enabled: true, screeners: [] }); w.handlers.change.forEach(f => f({ type: 'change', target: { id: 'ap-enabled', getAttribute: () => null } })); await sleep(30);
    check('switched on with nothing ticked: it stays on, waits, and says what to do', st.settings.enabled === true && st.settings.screeners.length === 0 && /On, but no screener is chosen yet/.test(w.text()) && /Autopilot switched on\. Tick at least one screener below for it to start\./.test(w.text()) && /id="ap-run"[^>]*disabled title="Tick at least one screener first"/.test(w.container.innerHTML), w.text().slice(0, 260));
  }
  // quick trading options
  { const OPT3 = { ...OPTIONS, everyHours: [0.5, 1, 3, 6, 12, 24], holdDays: [0.5 / 24, 1 / 24, 3 / 24, 6 / 24, 0.5, 1, 2, 5, 10, 20, 60] };
    const st = { settings: { ...settings, screeners: ['7-1'], everyHours: 0.5, maxHoldDays: 1 / 24 }, state: {}, log: [], practiceCash: 100000 };
    const w = page(b => { if (b.action === 'save') st.settings = b.settings; return { status: 200, body: { success: true, allowed: true, options: OPT3, ...st } }; }); await sleep(30);
    const html = w.container.innerHTML;
    check('check-ins from every 30 minutes and holdings from 30 minutes are offered in plain words', ['>every 30 minutes<', '>every hour<', '>every 3 hours<', '>twice a day<', '>once a day<', '>30 minutes<', '>1 hour<', '>3 hours<', '>12 hours<', '>1 day<', '>2 days<', '>60 days<'].every(x => html.includes(x)), html.slice(html.indexOf('ap-every'), html.indexOf('ap-every') + 300));
    check('the saved quick choices are the ones selected', /<option value="0\.5" selected>every 30 minutes</.test(html) && /<option value="0\.041666666666666664" selected>1 hour</.test(html), (html.match(/<option value="[^"]*" selected>[^<]*</g) || []));
    const said = () => w.els['ap-plan'].textContent + ' | ' + w.els['ap-pace'].textContent;
    check('quick settings on coins: the description names the check-in and the holding time chosen', /It checks in every 30 minutes\. Up to 6 holdings of about \$1,250 each at a time: .* That is \$7,500 of the \$10,000: it buys at most 3 at a check-in and sells each holding after 1 hour\./.test(w.text()) && /It sells a holding once it has had it for 1 hour, whatever the price/.test(w.text()) && /No trading costs are taken off here/.test(w.text()) && !/Shares are only traded/.test(w.text()), w.text().slice(w.text().indexOf('It checks in'), w.text().indexOf('It checks in') + 700));
    check('only coins ticked: the whole budget may go into coins, and it no longer says otherwise', !/only coin screeners are ticked, and the/.test(w.text()) && !/goes into coins at this level/.test(w.text()));
    const stub = () => ({ disabled: false, textContent: '', title: '', classList: { on: {}, toggle(c, v) { this.on[c] = v; } } });
    const fire = (type, id) => w.handlers[type].forEach(f => f({ type, target: { id, getAttribute: () => null } }));
    Object.assign(w.els, { 'ap-run': stub(), 'ap-saved': stub(), 'ap-plan': stub(), 'ap-pace': stub(), 'ap-chosen': stub(), 'ap-status': stub(), 'ap-switch-text': stub() });
    w.form({ ...st.settings, screeners: ['3-100'], everyHours: 24, maxHoldDays: 3 / 24 }); fire('change', 'ap-every');
    check('changing "Checks in" rewrites the description at once', /^It checks in once a day\. Up to 3 holdings of about \$1,250 each at a time: 1 at the first check-in, then more as the budget is released, all 3 after about 2 days\. That is \$3,750 of the \$10,000: it buys at most 3 at a check-in and sells each holding after 3 hours\. Keep holdings longer, or check in more often, for it to use more\. \|/.test(said()), said());
    check('a holding time shorter than the gap between check-ins: it says when the sale really happens', /It sells a holding once it has had it for 3 hours, whatever the price, .* It only checks in once a day, though, so in practice a holding is sold at the next check-in, about 1 day after it was bought\. Check in more often for it to be sold on time\. Shares are only traded while their market is open/.test(said()), said());
    w.form({ ...st.settings, screeners: ['3-100'], everyHours: 24, maxHoldDays: 5 }); fire('change', 'ap-hold');
    check('changing "Keeps a holding at most" rewrites it too', /all 8 after about 8 days\. Then the whole \$10,000 is in use\. \| It sells a holding once it has had it for 5 days, whatever the price/.test(said()) && !/though|No trading costs|Shares are only traded/.test(said()), said());
    w.form({ ...st.settings, screeners: ['3-100'], everyHours: 24, maxHoldDays: 2 }); fire('change', 'ap-hold');
    check('a 2-day holding time with daily check-ins: 6 of the 8 at most, and it says why', /Up to 6 holdings of about \$1,250 each at a time: .* That is \$7,500 of the \$10,000: it buys at most 3 at a check-in and sells each holding after 2 days\./.test(said()), said());
    w.form({ ...st.settings, screeners: ['7-1'], everyHours: 0.5, maxHoldDays: 0.5 / 24, risk: 5, periodDays: 1 }); fire('change', 'ap-hold');
    check('very short holdings: it says how little of the budget is ever in use', /It checks in every 30 minutes\. Up to 3 holdings of about \$2,500 each at a time: .* That is \$7,500 of the \$10,000: it buys at most 3 at a check-in and sells each holding after 30 minutes\. Keep holdings longer for it to use more\. A coin is only bought once it has been near the top at two check-ins running[^|]*\|/.test(said()), said());
    w.form({ ...st.settings, screeners: ['7-1'], risk: 1 }); fire('input', 'ap-risk');
    check('only coins at the Cautious level: coins are bought (ticking only coins asks for coins)', /Up to \d+ holdings of about \$833 each/.test(said()) && !/buy nothing/.test(said()) && !/goes into coins at this level/.test(said()), said());
    w.form({ ...st.settings, screeners: ['3-100', '7-1'], risk: 1, everyHours: 24, maxHoldDays: 20 }); fire('change', 'ap-screener');
    check('shares and coins ticked: it says how much of the budget the level puts in coins', /Up to 12 holdings of about \$833 each/.test(said()) && /Of that, at most 0% \(\$0\) goes into coins at this level\./.test(said()), said());
    w.form({ ...st.settings, screeners: ['3-100'], risk: 1, budgetUsd: 100 }); fire('input', 'ap-budget');
    check('a budget too small for the level: it says each buy would be under the smallest allowed', /The Cautious level spreads the budget over 12 holdings, which makes each about \$8: under the \$25 smallest buy, so it will buy nothing\. Raise the budget\./.test(said()), said());
    check('no broken values in any of these', !/undefined|NaN|Infinity|\[object/.test(said()));
    w.form({ ...st.settings, everyHours: 1, maxHoldDays: 3 / 24 }); await w.ctx.practiceAutopilot.flush(); await sleep(30);
    check('fractions of a day are saved exactly, not cut to whole numbers', st.settings.everyHours === 1 && st.settings.maxHoldDays === 0.125, st.settings);
    const slow = page(() => ({ status: 200, body: { success: true, allowed: true, options: OPT3, ...st, settings: { ...settings, screeners: ['3-100'] } } })); await sleep(30);
    check('with slow settings the notes about quick trading are not shown', /It sells a holding once it has had it for 20 days/.test(slow.text()) && !/quick settings|No trading costs/.test(slow.text()));
  }
  // what it holds, the month, its own rules and trials, details of a sale, and keeping itself up to date
  { const base = { settings: { ...settings, enabled: true, screeners: ['7-1'], everyHours: 0.5, maxHoldDays: 0.25 }, state: { lastRun: '2026-10-10T13:10:04Z' }, minSample: 8, practiceCash: 100000, scorecard: { n: 0, groups: {} },
      rules: { name: 'Balanced', stop: -10, take: 18, trail: 0.5, top: 10, max_rsi: 76, arm: 9, changed: {} }, tune: { trial: null, past: [], nextReviewIn: 20, batch: 20, group: 10, finished: 0 },
      month: { last30: { n: 0, up: 0, usd: 0, pct: 0 }, before30: { n: 0, up: 0, usd: 0, pct: 0 } },
      plans: [{ id: 'a1', label: 'WEMIX-USD', boughtAt: '2026-10-10T10:42:41Z', sellBy: '2026-10-10T16:42:41Z', auto: true, stop: -10, take: 18, arm: 9, trail: 0.5 }],
      log: [{ t: '2026-10-10T10:42:41Z', type: 'buy', symbol: 'WEMIX-USD', usd: 1250, text: 'rank 1, RSI 14 (Crypto (top coins) rank 1, score +4.0; chosen by the AI model)', detail: ['The plan for it: sell 6 hours after buying at the latest; sooner at -10% or +18%.'] },
            { t: '2026-10-10T13:10:04Z', first: '2026-10-10T11:10:04Z', n: 5, key: 'pace', type: 'note', symbol: '', usd: 0, text: 'Checked in. Nothing to spend yet: $1,250 of the $10,000 budget is invested. The rest is released in steps over the 10 days set under "Build up to it over"; the next $1,250 in about 21 hours.' }] };
    let now = JSON.parse(JSON.stringify(base)), gets = 0;
    const w = page(b => { if (b.action === 'get') gets++; return { status: 200, body: { success: true, allowed: true, options: OPTIONS, ...now } }; }); await sleep(30);
    check('how it is doing names what it holds and when it will sell it', /How it is doing Holding now: WEMIX-USD \(bought [^;]*; it sells it at the check-in around [^)]*\d\d:\d\d[^)]* at the latest, sooner at -10% or \+18%; a stop follows it once it has been up 9%\)\. No finished trades yet: nothing it bought has been sold\./.test(w.text()), w.text().slice(w.text().indexOf('How it is doing'), w.text().indexOf('How it is doing') + 300));
    check('it says the AI model also reviews each holding at every check-in', /At every check-in the AI model also reviews each holding against the latest screener figures and recent headlines, and may sell it earlier than these rules\./.test(w.text()));
    check('the practice portfolio is told the plan for each of its holdings', w.ctx.practicePortfolio.plans && w.ctx.practicePortfolio.plans[0].id === 'a1');
    check('improving its own rules: the rules in force and when it next reviews them', /Improving its own rules Its rules now \(Balanced level\): sells at -10% or \+18%; a stop follows a rising holding, set from how much that holding normally moves and from its screener figures now; buys from the top 10 of a ranking with RSI under 76\. Next review of its rules after 20 more finished trades \(it reviews them every 20\)\./.test(w.text()) && /It can only change these five rules, inside fixed limits, for its own fake-money trades\. It never changes your settings, the budget or anything else on the site\. Each review is emailed to your account address\./.test(w.text()), w.text().slice(w.text().indexOf('Improving its own rules'), w.text().indexOf('Improving its own rules') + 420));
    check('a buy has its plan under it, folded away', /<details data-ap-fold="buy2026-10-10T10:42:41ZWEMIX-USD" ><summary>The plan for it<\/summary><ul><li>The plan for it: sell 6 hours after buying at the latest; sooner at -10% or \+18%\.<\/li><\/ul><\/details>/.test(w.container.innerHTML));
    check('the same uneventful check-in is shown once, with how often', /Nothing to spend yet: \$1,250 of the \$10,000 budget is invested\. The rest is released in steps over the 10 days set under "Build up to it over"; the next \$1,250 in about 21 hours\. \(the same at 5 check-ins in a row, since [^)]*\)/.test(w.text()), w.text().slice(w.text().indexOf('What it has done'), w.text().indexOf('What it has done') + 420));
    check('the activity list says when it was last brought up to date and can be refreshed by hand', /What it has done Up to date at \d[^.]*\. Refreshes by itself every minute\. ↻ Refresh now/.test(w.text()) && /<a href="#" data-ap="refresh">/.test(w.container.innerHTML));
    // it sells while the page is open
    now = JSON.parse(JSON.stringify(base)); now.plans = []; now.scorecard = { label: 'all', n: 1, avg: 4.2, vs: 4.2, beat: 1, judged: 1, up: 1, groups: {} }; now.month.last30 = { n: 1, up: 1, usd: 52.5, pct: 0.53 }; now.tune.nextReviewIn = 19;
    now.log.push({ t: '2026-10-10T16:40:04Z', type: 'sell', symbol: 'WEMIX-USD', usd: 1302.5, kind: 'time', pct: 4.2, text: 'Held 6 hours, the longest this autopilot keeps a holding (+4.2%). Put in $1,250.00, got back $1,302.50.', detail: ['Bought at rank 1 of Crypto (top coins) (score +4.0, RSI 14), chosen by the AI model: rank 1, RSI 14.', 'Held 6 hours. It was set to keep a holding at most 6 hours.', 'While it was held: +5.1% at its best, -0.8% at its worst (as seen at check-ins).'] });
    const before = gets; await w.ctx.practiceAutopilot.refresh(false); await sleep(30);
    check('it brings itself up to date: a sale made in the background appears, with its result', gets === before + 1 && /Sold WEMIX-USD \+4\.2% \. Held 6 hours, the longest this autopilot keeps a holding \(\+4\.2%\)\. Put in \$1,250\.00, got back \$1,302\.50\./.test(w.text()) && /Holding nothing right now\./.test(w.text()), w.text().slice(w.text().indexOf('What it has done'), w.text().indexOf('What it has done') + 330));
    check('the sale has its story under it', /<summary>Why, and the details<\/summary><ul><li>Bought at rank 1 of Crypto \(top coins\)/.test(w.container.innerHTML) && /It was set to keep a holding at most 6 hours\./.test(w.text()) && /\+5\.1% at its best, -0\.8% at its worst/.test(w.text()));
    check('and the practice portfolio is reloaded and told its plans', w.ctx.practicePortfolio.reloaded === 1 && w.ctx.practicePortfolio.plans.length === 0);
    check('the last 30 days in dollars and as a share of the budget', /Last 30 days: \+\$52\.50 from 1 finished trade \(1 up\), which is \+0\.53% of the \$10,000 budget\./.test(w.text()) && /1 finished trade in all: 1 up, 0 down or level, average \+4\.2% each\. Fewer than 8 trades/.test(w.text()), w.text().slice(w.text().indexOf('How it is doing'), w.text().indexOf('How it is doing') + 300));
    const again = gets; await w.ctx.practiceAutopilot.refresh(false); await sleep(30);
    check('nothing new: it asks, and leaves the page and the portfolio alone', gets === again + 1 && w.ctx.practicePortfolio.reloaded === 1);
    now.plans = [{ id: 'b2', label: 'SOL-USD', boughtAt: '2026-10-10T16:40:04Z', sellBy: '2026-10-10T22:40:04Z', auto: true, stop: -10, take: 18, arm: 9, trail: 0.5, view: { t: '2026-10-10T17:10:04Z', sell: false, text: 'Rank 2 and score steady, no bad headline' } }];
    now.aiSellPausedUntil = null; await w.ctx.practiceAutopilot.refresh(false); await sleep(30);
    check('each holding shows the AI model\'s latest review of it', /Holding now: SOL-USD \(bought [^;]*; it sells it at the check-in around [^;]* at the latest, sooner at -10% or \+18%; a stop follows it once it has been up 9%; the AI model's latest review, [^:]*:\d\d[^:]*: keep \(Rank 2 and score steady, no bad headline\)\)\./.test(w.text()), w.text().slice(w.text().indexOf('Holding now'), w.text().indexOf('Holding now') + 300));
    now.aiSellPausedUntil = '2026-10-24T17:10:04Z'; now.tune = { ...now.tune, mark: 1 }; await w.ctx.practiceAutopilot.refresh(false); await sleep(30);
    check('a pause of its early sells is shown', /The AI model's early sells are paused until [^:]*2[45][^:]*: the holdings it had sold early went on rising afterwards\. The fixed selling rules still apply\./.test(w.text()), w.text().slice(w.text().indexOf('Improving its own rules'), w.text().indexOf('Improving its own rules') + 500));
    // a trial of one of its rules, then the result
    now.tune = { ...now.tune, nextReviewIn: null, trial: { id: 1, param: 'take', old: 18, new: 9, since: '2026-10-12T10:00:00Z', why: '10 of the last 20 finished trades were up 9% or more at some point while held, and ended at +1.0% on average', how: 'Every second buy follows the changed rule, the others the current one, so both are tried over the same days.', text: 'sell at +9% instead of "sell at +18%"', with: 3, without: 2, avgWith: 2.1, avgWithout: -0.4 } };
    await w.ctx.practiceAutopilot.refresh(false); await sleep(30);
    check('a trial of one of its rules is shown with its reason and how both groups are doing', /Trying now \(since [^)]*12[^)]*\): sell at \+9% instead of "sell at \+18%"\. Why: 10 of the last 20 finished trades were up 9% or more at some point while held, and ended at \+1\.0% on average\. Every second buy follows the changed rule, the others the current one, so both are tried over the same days\. So far: with the change 3 finished \(average \+2\.1%\), without it 2 finished \(average -0\.4%\)\. It decides after 10 each way and keeps the change only if that group did clearly better\./.test(w.text()), w.text().slice(w.text().indexOf('Trying now'), w.text().indexOf('Trying now') + 480));
    now.tune = { ...now.tune, nextReviewIn: 20, trial: null, past: [{ id: 1, param: 'take', old: 18, new: 9, since: '2026-10-12T10:00:00Z', ended: '2026-10-17T10:00:00Z', verdict: 'kept', text: 'sell at +9% instead of "sell at +18%"', result: '10 trades with the change averaged +3.20%, 10 without it +0.05% (difference +3.15, margin of error 0.31)' }] };
    now.rules = { ...now.rules, take: 9, arm: 4.5, changed: { take: 18 } };
    await w.ctx.practiceAutopilot.refresh(false); await sleep(30);
    check('a change it kept: the rules in force say so everywhere', /sells at -10% or \+9%; a stop follows a rising holding/.test(w.text()) && /Changed by itself after a trial: gain mark \(the level starts at 18\) put it back \./.test(w.text()) && /<a href="#" data-ap="restore" data-param="take">put it back<\/a>/.test(w.container.innerHTML) && /Balanced: spreads the budget over up to 8 holdings, looks at the top 10 of each screener, sells a holding at -10% or \+9%/.test(w.text()) && /and sooner at -10% or \+9%, when a stop that follows a rising holding is hit/.test(w.text()), w.text().slice(w.text().indexOf('Improving its own rules'), w.text().indexOf('Improving its own rules') + 300));
    check('and the earlier trial is listed with its verdict and numbers', /Earlier trials \(1\)/.test(w.text()) && /: sell at \+9% instead of "sell at \+18%": kept\. 10 trades with the change averaged \+3\.20%, 10 without it \+0\.05% \(difference \+3\.15, margin of error 0\.31\)\./.test(w.text()));
    check('no broken values in the new sections', !/undefined|NaN|\[object|Infinity/.test(w.container.innerHTML), (w.container.innerHTML.match(/.{40}(undefined|NaN|\[object|Infinity).{40}/) || [])[0]);
  }
  // managing it from the dashboard: quick set-ups, what it may do by itself, sell everything, its own rule changes, the list
  { const st = { settings: { ...settings, screeners: ['3-100'], aiSell: true, selfTune: true, emails: true }, state: {}, log: [{ t: '2026-10-10T10:42:41Z', type: 'buy', symbol: 'AMT', usd: 1250, text: 'rank 1' }, { t: '2026-10-10T11:10:04Z', type: 'note', symbol: '', usd: 0, text: 'Checked in. No change.' }], practiceCash: 100000,
      rules: { name: 'Balanced', stop: -10, take: 9, trail: 0.5, top: 10, max_rsi: 76, arm: 4.5, changed: { take: 18 } }, plans: [{ id: 'a1', label: 'AMT', boughtAt: '2026-10-10T10:42:41Z', sellBy: '2026-10-30T10:42:41Z', auto: true, stop: -10, take: 9, arm: 4.5 }],
      tune: { past: [], nextReviewIn: null, batch: 20, group: 10, trial: { id: 2, param: 'stop', old: -10, new: -5, since: '2026-10-12T10:00:00Z', why: 'w', how: 'h', text: 'sell at -5% instead of "sell at -10%"', with: 1, without: 1, avgWith: 1, avgWithout: 1 } } };
    const sent = [], OPTQ = { ...OPTIONS, everyHours: [0.5, 1, 3, 6, 12, 24], holdDays: [0.5 / 24, 1 / 24, 3 / 24, 0.25, 0.5, 1, 2, 5, 10, 20, 60] };
    const w = page(b => { sent.push(b); if (b.action === 'save') st.settings = b.settings; if (b.action === 'sellall') { st.plans = []; return { status: 200, body: { success: true, allowed: true, options: OPTQ, summary: { sold: 1, skipped: [] }, ...st } }; }
      if (b.action === 'tune' && b.op === 'stop') st.tune = { ...st.tune, trial: null, nextReviewIn: 20 }; if (b.action === 'tune' && b.op === 'restore') st.rules = { ...st.rules, take: 18, arm: 9, changed: {} };
      return { status: 200, body: { success: true, allowed: true, options: OPTQ, ...st } }; }); await sleep(30);
    const html = w.container.innerHTML;
    check('quick set-ups are offered for the screeners that exist', /Quick set-ups:/.test(w.text()) && /data-ap-preset="coins"[^>]*>⚡ Quick coin trading</.test(html) && /data-ap-preset="shares"/.test(html) && /data-ap-preset="mix"/.test(html) && /They fill in the fields below \(not the budget or the on\/off switch\)/.test(w.text()));
    check('what it may do by itself: three switches, on unless switched off', /What it may do by itself/.test(w.text()) && /<input id="ap-aisell" type="checkbox" checked>/.test(html) && /<input id="ap-tune" type="checkbox" checked>/.test(html) && /<input id="ap-mail" type="checkbox" checked>/.test(html) && /Sell early on the AI model's review/.test(w.text()) && /Try changes to its own rules/.test(w.text()) && /Email me its reviews/.test(w.text()));
    w.form({ ...st.settings }); const boxesNow = w.ctx.document.querySelectorAll('[data-ap-screener]');
    w.handlers.click.forEach(f => f({ target: { closest: sel => sel === '[data-ap-preset]' ? { getAttribute: () => 'coins' } : null }, preventDefault() {} })); await sleep(350);
    check('a quick set-up fills in the fields and saves them, leaving the budget and the switch alone', st.settings.risk === 4 && st.settings.periodDays === 1 && st.settings.everyHours === 0.5 && st.settings.maxHoldDays === 0.25 && JSON.stringify(st.settings.screeners) === '["7-1"]' && st.settings.budgetUsd === 10000 && st.settings.enabled === false && boxesNow.filter(b => b.checked).length === 1, st.settings);
    w.form({ ...st.settings }); Object.assign(w.els, { 'ap-aisell': { checked: false }, 'ap-tune': { checked: true }, 'ap-mail': { checked: false } }); await w.ctx.practiceAutopilot.flush(); await sleep(30);
    check('switching one of them off is saved like any other setting', st.settings.aiSell === false && st.settings.selfTune === true && st.settings.emails === false && /<input id="ap-aisell" type="checkbox" >/.test(w.container.innerHTML), st.settings);
    delete w.els['ap-aisell']; delete w.els['ap-tune']; delete w.els['ap-mail'];
    check('sell everything it holds: offered with the number it holds', /<button id="ap-sellall" data-ap="sellall" class="ap-btn" [^>]*>Sell everything it holds \(1\)<\/button>/.test(w.container.innerHTML) && !/id="ap-sellall"[^>]*disabled/.test(w.container.innerHTML));
    w.ctx.answer = false; w.form({ ...st.settings }); w.click('sellall'); await sleep(40);
    check('it asks first, and does nothing if you say no', /Sell the 1 holding the autopilot bought, now, at the latest prices\?/.test(w.ctx.asked) && /Holdings you bought yourself are not touched/.test(w.ctx.asked) && !sent.some(b => b.action === 'sellall'));
    w.ctx.answer = true; w.click('sellall'); await sleep(60);
    check('on yes it sells, says so, and the practice portfolio is reloaded', sent.some(b => b.action === 'sellall') && /Sold 1 holding\./.test(w.text()) && w.ctx.practicePortfolio.reloaded === 1 && /id="ap-sellall"[^>]*disabled title="It holds nothing right now"/.test(w.container.innerHTML), w.text().slice(w.text().indexOf('Sold 1'), w.text().indexOf('Sold 1') + 120));
    w.form({ ...st.settings }); w.handlers.click.forEach(f => f({ target: { closest: sel => sel === '[data-ap]' ? { getAttribute: k => k === 'data-ap' ? 'stoptrial' : null, tagName: 'A' } : null }, preventDefault() {} })); await sleep(60);
    check('its running trial can be stopped from the page', sent.some(b => b.action === 'tune' && b.op === 'stop') && !/Trying now/.test(w.text()) && /Trial stopped\. The rule stays as it was\./.test(w.text()));
    w.form({ ...st.settings }); w.handlers.click.forEach(f => f({ target: { closest: sel => sel === '[data-ap]' ? { getAttribute: k => k === 'data-ap' ? 'restore' : 'take', tagName: 'A' } : null }, preventDefault() {} })); await sleep(60);
    check('a rule it changed can be put back from the page', sent.some(b => b.action === 'tune' && b.op === 'restore' && b.param === 'take') && !/Changed by itself/.test(w.text()) && /sells at -10% or \+18%/.test(w.text()));
    check('the activity list shows everything to start with, with a switch for "buys and sells only"', /Checked in\. No change\./.test(w.text()) && /<label class="ap-mini"[^>]*><input id="ap-tradesonly" type="checkbox" ><span class="ap-dot"><\/span>Buys and sells only<\/label>/.test(w.container.innerHTML) && !/data-ap="filter"/.test(w.container.innerHTML));
    const savesBefore = sent.filter(b => b.action === 'save').length;
    w.form({ ...st.settings }); w.handlers.change.forEach(f => f({ type: 'change', target: { id: 'ap-tradesonly', checked: true, getAttribute: () => null } })); await sleep(300);
    check('switching it on cuts the list down to buys and sells', !/Checked in\. No change\./.test(w.text()) && /Bought AMT/.test(w.text()) && /<input id="ap-tradesonly" type="checkbox" checked>/.test(w.container.innerHTML));
    check('it is a way of looking at the list, not a setting: nothing is sent to be saved', sent.filter(b => b.action === 'save').length === savesBefore && kept.stockiqAutopilotTradesOnly === '1', [sent.filter(b => b.action === 'save').length, savesBefore, kept]);
    const again = page(b => ({ status: 200, body: { success: true, allowed: true, options: OPTQ, ...st } })); await sleep(30);
    check('after a refresh the switch is still on and the list still shows buys and sells only', /<input id="ap-tradesonly" type="checkbox" checked>/.test(again.container.innerHTML) && !/Checked in\. No change\./.test(again.text()) && /Bought AMT/.test(again.text()));
    again.form({ ...st.settings }); again.handlers.change.forEach(f => f({ type: 'change', target: { id: 'ap-tradesonly', checked: false, getAttribute: () => null } })); await sleep(30);
    const third = page(b => ({ status: 200, body: { success: true, allowed: true, options: OPTQ, ...st } })); await sleep(30);
    check('switched off again, that is remembered too', kept.stockiqAutopilotTradesOnly === '0' && /Checked in\. No change\./.test(third.text()) && /<input id="ap-tradesonly" type="checkbox" >/.test(third.container.innerHTML));
    check('no broken values among the controls', !/undefined|NaN|\[object|Infinity/.test(w.container.innerHTML), (w.container.innerHTML.match(/.{40}(undefined|NaN|\[object|Infinity).{40}/) || [])[0]);
  }
  // a gain worth keeping follows the holding time (the same sum as gain_arm in the Lambda; the same cases are checked in ai_trader_test.py)
  { const st = { settings: { ...settings, enabled: true, screeners: ['7-1'], everyHours: 0.5, maxHoldDays: 0.25, aiSell: true, selfTune: true, emails: true, stopPct: null, takePct: null }, state: {}, log: [], practiceCash: 100000, scorecard: { n: 0, groups: {} },
      rules: { name: 'Balanced', stop: -10, take: 18, trail: 0.5, top: 10, max_rsi: 76, arm: 1, changed: {}, yours: [], level: { stop: -10, take: 18 } }, tune: { past: [], trial: null, nextReviewIn: 20, batch: 20, group: 10 },
      plans: [{ id: 'a1', label: 'CFX-USD', boughtAt: '2026-10-10T14:35:27Z', sellBy: '2026-10-10T20:35:27Z', auto: true, stop: -10, take: 18, arm: 1, trail: 0.5, peak: 4.2, floor: 2.3, view: { t: '2026-10-10T15:10:04Z', sell: false, text: 'Up 4% and still climbing', larger: true } }] };
    const OPTH = { ...OPTIONS, everyHours: [0.5, 1, 3, 6, 12, 24], holdDays: [0.5 / 24, 1 / 24, 0.25, 1, 5, 20, 60] };
    const w = page(b => ({ status: 200, body: { success: true, allowed: true, options: OPTH, ...st } })); await sleep(30);
    check('the description says the stop is set from each holding\'s own movement, not a fixed number', /when a stop that follows a rising holding is hit \(it starts once the holding has risen beyond its own normal wobble and is set from how much that holding normally moves: wider for a jumpy coin, closer when its screener figures weaken or time is short\)/.test(w.text()) && /a stop follows a rising holding, set from how much that holding normally moves and from its screener figures now/.test(w.text()) && !/once it has been up 1%/.test(w.text()), w.text().slice(w.text().indexOf('It sells a holding'), w.text().indexOf('It sells a holding') + 330));
    check('a holding that has been up says what is now protected, and who last reviewed it', /Holding now: CFX-USD \(bought [^;]*; it sells it at the check-in around [^;]* at the latest, sooner at -10% or \+18%; it has been up \+4\.2% at its best and is sold if it slips back to \+2\.3%; the AI model's latest review, [^:]*:\d\d[^:]*, by the larger model: keep \(Up 4% and still climbing\)\)\./.test(w.text()), w.text().slice(w.text().indexOf('Holding now'), w.text().indexOf('Holding now') + 380));
    const stub = () => ({ disabled: false, textContent: '', title: '', placeholder: '', classList: { on: {}, toggle(c, v) { this.on[c] = v; } } });
    Object.assign(w.els, { 'ap-run': stub(), 'ap-saved': stub(), 'ap-plan': stub(), 'ap-pace': stub(), 'ap-chosen': stub(), 'ap-status': stub(), 'ap-switch-text': stub() });
    st.plans = [{ id: 'a1', label: 'CFX-USD', boughtAt: '2026-10-10T14:35:27Z', sellBy: '2026-10-10T20:35:27Z', auto: true, stop: -10, take: 18, arm: 1.4, trail: 0.5, peak: 6.15, floor: 3.9, move: 0.91, room: 2.5, tight: false, view: { t: '2026-10-10T15:40:04Z', sell: false, tighten: true, text: 'Up 6% but volume is fading', larger: true } },
                { id: 'a2', label: 'SOL-USD', boughtAt: '2026-10-10T15:40:04Z', sellBy: '2026-10-10T21:40:04Z', auto: true, stop: -10, take: 18, arm: 1.2, trail: 0.5, peak: 0.4, floor: null, move: 0.8, room: 2, tight: true }];
    await w.ctx.practiceAutopilot.refresh(false); await sleep(30);
    check('each holding shows its own stop: how much it normally moves, how far it may slip, and a tighter stop the review asked for', /CFX-USD \([^)]*it has been up \+6\.2% at its best and is sold if it slips back to \+3\.9% \(it normally moves about 0\.9% between check-ins and may slip 2\.5 such moves from its best\); the AI model's latest review, [^:]*:\d\d[^:]*, by the larger model: keep, with a tighter stop \(Up 6% but volume is fading\)\)/.test(w.text()) && /SOL-USD \([^)]*a stop follows it once it has been up 1\.2% \(it normally moves about 0\.8% between check-ins and may slip 2 such moves from its best; the AI review asked for a tighter stop\)\)/.test(w.text()), w.text().slice(w.text().indexOf('Holding now'), w.text().indexOf('Holding now') + 800));
    check('it says a larger model is asked when a gain is at stake', /A larger model is asked when a gain is at stake \(a few times a day at most\)/.test(w.text()));
  }
  // the pace (build-up, check-in gap, holding time) follows the risk level unless it is set by hand
  { const PACE = { 1: { periodDays: 10, everyHours: 24, maxHoldDays: 20 }, 3: { periodDays: 5, everyHours: 6, maxHoldDays: 5 }, 5: { periodDays: 1, everyHours: 1, maxHoldDays: 1 } };
    const OPTP = { ...OPTIONS, pace: PACE, everyHours: [0.5, 1, 3, 6, 12, 24], holdDays: [0.5 / 24, 1 / 24, 0.25, 1, 2, 5, 10, 20, 60] };
    const all = ['periodDays', 'everyHours', 'maxHoldDays'];
    const st = { settings: { ...settings, screeners: ['3-100'], periodDays: 5, everyHours: 6, maxHoldDays: 5, aiSell: true, selfTune: true, emails: true, stopPct: null, takePct: null, auto: all }, state: {}, log: [], practiceCash: 100000,
      rules: { name: 'Balanced', stop: -10, take: 18, trail: 0.5, top: 10, max_rsi: 76, arm: 4.5, changed: {}, yours: [], level: { stop: -10, take: 18 } }, plans: [], tune: { past: [], trial: null, nextReviewIn: 20, batch: 20, group: 10 } };
    let saves = 0;
    const w = page(b => { if (b.action === 'save') { saves++; st.settings = b.settings; } return { status: 200, body: { success: true, allowed: true, options: OPTP, ...st } }; }); await sleep(30);
    const html = () => w.container.innerHTML;
    check('left to the level, the three pace fields show "automatic" with the level\'s own value', /<input id="ap-period" type="number" min="1" max="90" step="1" placeholder="5" value="">/.test(html()) && /<select id="ap-every"><option value="auto" selected>Automatic: every 6 hours<\/option>/.test(html()) && /<select id="ap-hold"><option value="auto" selected>Automatic: 5 days<\/option>/.test(html()) && (html().match(/class="ap-auto ">automatic</g) || []).length === 3 && !/data-ap="autopace"/.test(html()), html().slice(html().indexOf('ap-period') - 120, html().indexOf('ap-period') + 260));
    check('the level\'s sentence says the pace it sets, and the description uses it', /Left to the level, it builds the budget up over 5 days, checks in every 6 hours and keeps a holding at most 5 days\./.test(w.text()) && /It checks in every 6 hours\. Up to 8 holdings/.test(w.text()) && /It sells a holding once it has had it for 5 days/.test(w.text()) && /The last three follow the risk level while they are left on automatic/.test(w.text()));
    const stub = () => ({ disabled: false, textContent: '', title: '', placeholder: '', classList: { on: {}, toggle(c, v) { this.on[c] = v; } } });
    const fresh = () => Object.assign(w.els, { 'ap-run': stub(), 'ap-saved': stub(), 'ap-plan': stub(), 'ap-pace': stub(), 'ap-chosen': stub(), 'ap-status': stub(), 'ap-switch-text': stub(), 'ap-tag-periodDays': stub(), 'ap-tag-everyHours': stub(), 'ap-tag-maxHoldDays': stub() });
    const leave = (...keys) => { if (keys.includes('periodDays')) w.els['ap-period'].value = ''; if (keys.includes('everyHours')) w.els['ap-every'].value = 'auto'; if (keys.includes('maxHoldDays')) w.els['ap-hold'].value = 'auto'; };
    fresh(); w.form({ ...st.settings, risk: 5 }); leave(...all); Object.assign(w.els['ap-every'], { options: [{ value: 'auto', textContent: '' }] }); Object.assign(w.els['ap-hold'], { options: [{ value: 'auto', textContent: '' }] });
    w.handlers.input.forEach(f => f({ type: 'input', target: { id: 'ap-risk', getAttribute: () => null } }));
    check('moving the slider moves all three at once: the description, the greyed values and the menus', /^It checks in every hour\. Up to 4 holdings/.test(w.els['ap-plan'].textContent) && /once it has had it for 1 day/.test(w.els['ap-pace'].textContent) && w.els['ap-period'].placeholder === '1' && w.els['ap-every'].options[0].textContent === 'Automatic: every hour' && w.els['ap-hold'].options[0].textContent === 'Automatic: 1 day' && /Left to the level, it builds the budget up over 1 day, checks in every hour and keeps a holding at most 1 day\./.test(w.els['ap-risk-text'].textContent), [w.els['ap-plan'].textContent.slice(0, 60), w.els['ap-period'].placeholder, w.els['ap-every'].options[0].textContent]);
    await sleep(1100);
    check('and what is saved is the level\'s pace, still left to the level', saves === 1 && st.settings.risk === 5 && st.settings.periodDays === 1 && st.settings.everyHours === 1 && st.settings.maxHoldDays === 1 && JSON.stringify(st.settings.auto) === JSON.stringify(all), st.settings);
    fresh(); w.form({ ...st.settings }); leave('periodDays', 'everyHours'); w.els['ap-hold'].value = '0.25'; w.handlers.change.forEach(f => f({ type: 'change', target: { id: 'ap-hold', getAttribute: () => null } })); await sleep(300);
    check('setting one yourself fixes that one; the other two stay with the level', saves === 2 && st.settings.maxHoldDays === 0.25 && JSON.stringify(st.settings.auto) === '["periodDays","everyHours"]' && /Keeps a holding at most<span id="ap-tag-maxHoldDays" class="ap-auto own">set by you<\/span>/.test(html()) && /<option value="0\.25" selected>6 hours<\/option>/.test(html()) && /<option value="auto" >Automatic: 1 day<\/option>/.test(html()) && /data-ap="autopace">Let the risk level set all three<\/a>/.test(html()), [saves, st.settings.auto, st.settings.maxHoldDays]);
    fresh(); w.form({ ...st.settings, risk: 1 }); leave('periodDays', 'everyHours'); await w.ctx.practiceAutopilot.flush(); await sleep(30);
    check('moving the level now moves only the two left to it', st.settings.risk === 1 && st.settings.periodDays === 10 && st.settings.everyHours === 24 && st.settings.maxHoldDays === 0.25 && JSON.stringify(st.settings.auto) === '["periodDays","everyHours"]', st.settings);
    fresh(); w.form({ ...st.settings }); leave('periodDays', 'everyHours'); w.handlers.click.forEach(f => f({ target: { closest: sel => sel === '[data-ap]' ? { getAttribute: () => 'autopace', tagName: 'A' } : null }, preventDefault() {} })); await sleep(300);
    check('"Let the risk level set all three" hands the third one back', st.settings.maxHoldDays === 20 && JSON.stringify(st.settings.auto) === JSON.stringify(all) && /The risk level now sets how fast it builds up, how often it checks in and how long it keeps a holding\./.test(w.text()) && !/data-ap="autopace"/.test(html()), st.settings);
    const old = page(b => ({ status: 200, body: { success: true, allowed: true, options: OPTP, ...st, settings: { ...st.settings, periodDays: 1, everyHours: 0.5, maxHoldDays: 0.25, auto: [] } } })); await sleep(30);
    check('settings chosen by hand before this existed are shown as set by you, with the way back', (old.container.innerHTML.match(/class="ap-auto own">set by you</g) || []).length === 3 && /<input id="ap-period"[^>]*placeholder="10" value="1">/.test(old.container.innerHTML) && /<option value="0\.5" selected>every 30 minutes<\/option>/.test(old.container.innerHTML) && /data-ap="autopace"/.test(old.container.innerHTML));
    check('no broken values around the pace', !/undefined|NaN|\[object|Infinity/.test(html()) && !/undefined|NaN|\[object|Infinity/.test(old.container.innerHTML));
  }
  // waiting for a coin to stay near the top; results after a typical trading cost; the record by time on the shortlist
  { const G2 = (label, n, avg) => ({ label, n, avg, vs: null, beat: 0, judged: 0, up: avg > 0 ? n : 0 });
    const st = { settings: { ...settings, enabled: true, screeners: ['7-1'], everyHours: 0.5, maxHoldDays: 0.25 }, state: {}, log: [], minSample: 8, practiceCash: 100000, costEachWay: 0.1, plans: [],
      month: { last30: { n: 2, up: 1, usd: 30, pct: 0.3, afterCosts: 23.97 }, before30: { n: 0, up: 0, usd: 0, pct: 0, afterCosts: 0 } },
      scorecard: { ...G2('all', 9, 1.2), groups: { stay: [G2('new to the shortlist', 3, -1.0), G2('there 2 to 4 check-ins', 4, 2.0), G2('there 5 check-ins or more', 2, 3.0)] } } };
    const OPTC = { ...OPTIONS, everyHours: [0.5, 1, 3, 6, 12, 24], holdDays: [0.5 / 24, 1 / 24, 0.25, 1, 5, 20, 60] };
    const w = page(b => ({ status: 200, body: { success: true, allowed: true, options: OPTC, ...st } })); await sleep(30);
    check('with coins and quick check-ins it says a coin is bought only once it has stayed near the top', /A coin is only bought once it has been near the top at two check-ins running \(coin rankings change fast and many drop out again within the hour\), so coin buying starts one check-in later than this\./.test(w.text()));
    check('the last 30 days are also given after a typical trading cost', /Last 30 days: \+\$30\.00 from 2 finished trades \(1 up\), which is \+0\.30% of the \$10,000 budget\. No trading costs are taken from the fake money: with a typical 0\.1% on each buy and each sell that would be \+\$23\.97 \./.test(w.text()), w.text().slice(w.text().indexOf('Last 30 days'), w.text().indexOf('Last 30 days') + 260));
    check('the breakdown shows how buys did by how long they had stayed near the top', /By how long it had stayed near the top when bought new to the shortlist 3 -1\.0% 0 of 3 – there 2 to 4 check-ins 4 \+2\.0% 4 of 4 – there 5 check-ins or more 2 \+3\.0% 2 of 2 –/.test(w.text()), w.text().slice(w.text().indexOf('By how long'), w.text().indexOf('By how long') + 220));
    const slow = page(b => ({ status: 200, body: { success: true, allowed: true, options: OPTC, ...st, settings: { ...st.settings, everyHours: 24 } } })); await sleep(30);
    const shares = page(b => ({ status: 200, body: { success: true, allowed: true, options: OPTC, ...st, settings: { ...st.settings, screeners: ['3-100'] } } })); await sleep(30);
    check('not when it checks in once a day, and not for shares', !/A coin is only bought once/.test(slow.text()) && !/A coin is only bought once/.test(shares.text()));
  }
  // your own loss limit and gain mark
  { const st = { settings: { ...settings, screeners: ['3-100'], aiSell: true, selfTune: true, emails: true, stopPct: null, takePct: null }, state: {}, log: [], practiceCash: 100000, realizedUsd: 7.91,
      rules: { name: 'Balanced', stop: -10, take: 18, trail: 0.5, top: 10, max_rsi: 76, arm: 9, changed: {}, yours: [], level: { stop: -10, take: 18 } }, plans: [], tune: { past: [], trial: null, nextReviewIn: 20, batch: 20, group: 10 } };
    let saves = 0;
    const w = page(b => { if (b.action === 'save') { saves++; st.settings = b.settings; const mine = [b.settings.stopPct ? 'stop' : null, b.settings.takePct ? 'take' : null].filter(Boolean); st.rules = { ...st.rules, stop: b.settings.stopPct ? -b.settings.stopPct : -10, take: b.settings.takePct || 18, arm: (b.settings.takePct || 18) / 2, yours: mine }; }
      return { status: 200, body: { success: true, allowed: true, options: OPTIONS, ...st } }; }); await sleep(30);
    check('two optional fields for your own loss limit and gain mark, empty to start, the level\'s shown in grey', /<input id="ap-stop" type="number" min="1\.5" max="30" step="0\.5" inputmode="decimal" placeholder="10" value=""/.test(w.container.innerHTML) && /<input id="ap-take" type="number" min="2" max="80" step="0\.5" inputmode="decimal" placeholder="18" value=""/.test(w.container.innerHTML) && /Your own limits Sell at a loss of % Sell at a gain of % Optional\. Leave a field empty to use the level's \(shown in grey\)\. What you set here, its own trials leave alone\./.test(w.text()), w.text().slice(w.text().indexOf('Your own limits'), w.text().indexOf('Your own limits') + 200));
    check('the practice portfolio is told what its finished trades have made', w.ctx.practicePortfolio.extra && w.ctx.practicePortfolio.extra.realizedUsd === 7.91);
    const stub = () => ({ disabled: false, textContent: '', title: '', placeholder: '', classList: { on: {}, toggle(c, v) { this.on[c] = v; } } });
    Object.assign(w.els, { 'ap-run': stub(), 'ap-saved': stub(), 'ap-plan': stub(), 'ap-pace': stub(), 'ap-chosen': stub(), 'ap-status': stub(), 'ap-switch-text': stub() });
    w.form({ ...st.settings }); Object.assign(w.els, { 'ap-stop': { value: '6', placeholder: '' }, 'ap-take': { value: '', placeholder: '' } });
    w.handlers.input.forEach(f => f({ type: 'input', target: { id: 'ap-stop', getAttribute: () => null } }));
    check('typing your own loss limit: the descriptions follow at once', /sells a holding at -6% or \+18%/.test(w.els['ap-risk-text'].textContent) && /and sooner at -6% or \+18%/.test(w.els['ap-pace'].textContent) && saves === 0, [w.els['ap-risk-text'].textContent, w.els['ap-pace'].textContent.slice(0, 120)]);
    await sleep(1100);
    check('and it is saved by itself, as a size in percent', saves === 1 && st.settings.stopPct === 6 && st.settings.takePct === null && /value="6"/.test(w.container.innerHTML) && /Set by you: loss limit; its trials leave that alone\./.test(w.text()), [saves, st.settings.stopPct, w.text().slice(w.text().indexOf('Its rules now'), w.text().indexOf('Its rules now') + 260)]);
    Object.assign(w.els, { 'ap-run': stub(), 'ap-saved': stub(), 'ap-plan': stub(), 'ap-pace': stub(), 'ap-chosen': stub(), 'ap-status': stub(), 'ap-switch-text': stub() });
    w.form({ ...st.settings }); Object.assign(w.els, { 'ap-stop': { value: '6', placeholder: '' }, 'ap-take': { value: '500', placeholder: '' } }); await w.ctx.practiceAutopilot.flush(); await sleep(30);
    check('a gain mark that makes no sense is not saved, and it says why', saves === 1 && w.els['ap-saved'].textContent === 'Not saved: your own gain mark must be between 2% and 80% (or empty).', w.els['ap-saved'].textContent);
    w.form({ ...st.settings }); Object.assign(w.els, { 'ap-stop': { value: '', placeholder: '' }, 'ap-take': { value: '12.5', placeholder: '' } }); await w.ctx.practiceAutopilot.flush(); await sleep(30);
    check('emptying a field goes back to the level\'s', saves === 2 && st.settings.stopPct === null && st.settings.takePct === 12.5 && /sells a holding at -10% or \+12\.5%/.test(w.text()) && /Set by you: gain mark; its trials leave that alone\./.test(w.text()), st.settings);
    delete w.els['ap-stop']; delete w.els['ap-take'];
    check('no broken values around the limits', !/undefined|NaN|\[object|Infinity/.test(w.container.innerHTML));
  }
  check('no broken values', !/undefined|NaN|\[object/.test(p.container.innerHTML), (p.container.innerHTML.match(/.{30}(undefined|NaN|\[object).{30}/) || [])[0]);
  console.log(ok ? 'ALL PASS' : 'SOME FAILED');
})();
